variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - build


build kexing-management dev:
  image: registry.yunmotec.com:1443/gradle:7.3.3-jdk11
  tags:
    - java
  stage: build
  script:
    - gradle jib -Djib.to.image=registry.yunmotec.com:1443/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID -Djib.disableUpdateChecks=true -Djib.allowInsecureRegistries=true
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - management-infrastruction/build
      - management-api-rpc/build
      - management-domain/build
      - management-api-rest/build
      - .gradle
  only:
    - develop

build kexing-management qa:
  image: registry.yunmotec.com:1443/gradle:7.3.3-jdk11
  tags:
    - java
  stage: build
  script:
    - gradle jib -Djib.to.image=registry.yunmotec.com:1443/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - management-infrastruction/build
      - management-api-rpc/build
      - management-domain/build
      - management-api-rest/build
      - .gradle
  only:
    - qa

build kexing-management prod:
  image: registry.yunmotec.com:1443/gradle:7.3.3-jdk11
  tags:
    - java
  stage: build
  script:
    - gradle jib -Djib.to.auth.username="泉信技术" -Djib.to.auth.password="mBB@vY@n5xQmXmh" -Djib.to.image=registry.cn-beijing.aliyuncs.com/quanxinbim/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME.$CI_PIPELINE_IID
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - management-infrastruction/build
      - management-api-rpc/build
      - management-domain/build
      - management-api-rest/build
      - .gradle
  except:
    - develop
    - /^release.*$/
    - /^feature.*$/
  only:
    - tags
