package org.kexing.management.domin.model.mysql.robot;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.yunmo.generator.annotation.AutoValueDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import lombok.experimental.Accessors;
import org.hibernate.annotations.*;

import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;

/**
 * @author lh
 */
@Entity
@Data
@Builder
@AutoValueDTO
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@Schema(description = "巡检机器人巡检路线")
@Table
public class RobotPatrolLine {
  @Id
  @GenericGenerator(name = "sequence_id", strategy = "com.yunmo.id.HibernateIdentifierGenerator")
  @GeneratedValue(generator = "sequence_id")
  @NotNull
  private Long id;

  private String name;

  @Schema(description = "巡检任务编号")
  @Column(nullable = false)
  private String patrolNum;

  private Long robotId;

  @Column(columnDefinition = "json")
  @Type(type = "json")
  private List<AreaPoint> areaPoints;

  @Column(length = 500)
  private String lineMap;


  @Setter
  @Getter
  @Builder
  @Schema(description = "区域")
  @AllArgsConstructor
  @NoArgsConstructor
  @EqualsAndHashCode
  public static class AreaPoint {
    private List<Point> points;

    @Schema(description = "区域名称")
    private String areName;

    @Setter
    @Getter
    @Builder
    @Schema(description = "坐标点")
    @AllArgsConstructor
    @NoArgsConstructor
    @EqualsAndHashCode
    public static class Point {
      private Double pointX;
      private Double pointY;
    }
  }

  @SneakyThrows
  public static void main(String[] args) {
    String patrolJson =
            "{\n"
                    + "    \"patrol\": [\n"
                    + "        {\n"
                    + "            \"patrol_num\": \"0720102138\",\n"
                    + "            \"patrol_point\": [\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"1\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"135\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.7\",\n"
                    + "                    \"point_y\": \"10.08\",\n"
                    + "                    \"point_yaw\": \"-1\"\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"patrol_text\": \"2022/07/20/ 10:21:38\"\n"
                    + "        },\n"
                    + "        {\n"
                    + "            \"patrol_num\": \"0720134408\",\n"
                    + "            \"patrol_point\": [\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.7\",\n"
                    + "                    \"point_y\": \"10.08\",\n"
                    + "                    \"point_yaw\": \"-2\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.8\",\n"
                    + "                    \"point_y\": \"7.9\",\n"
                    + "                    \"point_yaw\": \"3.14\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"1\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"10.7\",\n"
                    + "                    \"point_y\": \"13.1\",\n"
                    + "                    \"point_yaw\": \"0.2\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"10.8\",\n"
                    + "                    \"point_y\": \"23.7\",\n"
                    + "                    \"point_yaw\": \"1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"4.76\",\n"
                    + "                    \"point_y\": \"23.9\",\n"
                    + "                    \"point_yaw\": \"0.75\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"5.31\",\n"
                    + "                    \"point_y\": \"29.31\",\n"
                    + "                    \"point_yaw\": \"-0.7\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"1\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"14.5\",\n"
                    + "                    \"point_y\": \"29.2\",\n"
                    + "                    \"point_yaw\": \"-1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"19.5\",\n"
                    + "                    \"point_y\": \"29\",\n"
                    + "                    \"point_yaw\": \"-2.32\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"19.2\",\n"
                    + "                    \"point_y\": \"24\",\n"
                    + "                    \"point_yaw\": \"2.355\"\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"patrol_text\": \"2022/07/20/ 13:44:08\"\n"
                    + "        },\n"
                    + "        {\n"
                    + "            \"patrol_num\": \"0720161235\",\n"
                    + "            \"patrol_point\": [\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.7\",\n"
                    + "                    \"point_y\": \"10.08\",\n"
                    + "                    \"point_yaw\": \"0\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.8\",\n"
                    + "                    \"point_y\": \"7.9\",\n"
                    + "                    \"point_yaw\": \"3.14\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"10.7\",\n"
                    + "                    \"point_y\": \"13.1\",\n"
                    + "                    \"point_yaw\": \"1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"10.8\",\n"
                    + "                    \"point_y\": \"23.7\",\n"
                    + "                    \"point_yaw\": \"1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"4.76\",\n"
                    + "                    \"point_y\": \"23.9\",\n"
                    + "                    \"point_yaw\": \"0.75\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"5.31\",\n"
                    + "                    \"point_y\": \"29.31\",\n"
                    + "                    \"point_yaw\": \"-0.7\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"14.5\",\n"
                    + "                    \"point_y\": \"29.2\",\n"
                    + "                    \"point_yaw\": \"-1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"19.5\",\n"
                    + "                    \"point_y\": \"29\",\n"
                    + "                    \"point_yaw\": \"-2.32\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"19.2\",\n"
                    + "                    \"point_y\": \"24\",\n"
                    + "                    \"point_yaw\": \"2.355\"\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"patrol_text\": \"2022/07/20/ 16:12:35\"\n"
                    + "        },\n"
                    + "        {\n"
                    + "            \"patrol_num\": \"0720175921\",\n"
                    + "            \"patrol_point\": [\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.7\",\n"
                    + "                    \"point_y\": \"10.08\",\n"
                    + "                    \"point_yaw\": \"0\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.8\",\n"
                    + "                    \"point_y\": \"7.9\",\n"
                    + "                    \"point_yaw\": \"3.14\"\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"patrol_text\": \"2022/07/20/ 17:59:21\"\n"
                    + "        },\n"
                    + "        {\n"
                    + "            \"patrol_num\": \"0721092120\",\n"
                    + "            \"patrol_point\": [\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.7\",\n"
                    + "                    \"point_y\": \"10.08\",\n"
                    + "                    \"point_yaw\": \"0\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"13.8\",\n"
                    + "                    \"point_y\": \"7.9\",\n"
                    + "                    \"point_yaw\": \"3.14\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"10.7\",\n"
                    + "                    \"point_y\": \"13.1\",\n"
                    + "                    \"point_yaw\": \"1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"10.8\",\n"
                    + "                    \"point_y\": \"23.7\",\n"
                    + "                    \"point_yaw\": \"1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"4.76\",\n"
                    + "                    \"point_y\": \"23.9\",\n"
                    + "                    \"point_yaw\": \"0.75\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"5.31\",\n"
                    + "                    \"point_y\": \"29.31\",\n"
                    + "                    \"point_yaw\": \"-0.7\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"14.5\",\n"
                    + "                    \"point_y\": \"29.2\",\n"
                    + "                    \"point_yaw\": \"-1.57\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"19.5\",\n"
                    + "                    \"point_y\": \"29\",\n"
                    + "                    \"point_yaw\": \"-2.32\"\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"patrol_do\": [\n"
                    + "                        {\n"
                    + "                            \"camera_picture\": \"1\",\n"
                    + "                            \"camera_video\": \"1\",\n"
                    + "                            \"find_light\": \"0\",\n"
                    + "                            \"find_num\": \"0\",\n"
                    + "                            \"find_tep\": \"0\",\n"
                    + "                            \"infrared_picture\": \"1\",\n"
                    + "                            \"infrared_video\": \"1\",\n"
                    + "                            \"robot_head_h\": \"90\",\n"
                    + "                            \"robot_head_v\": \"90\"\n"
                    + "                        }\n"
                    + "                    ],\n"
                    + "                    \"point_x\": \"19.2\",\n"
                    + "                    \"point_y\": \"24\",\n"
                    + "                    \"point_yaw\": \"2.355\"\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"patrol_text\": \"2022/07/21/ 09:21:20\"\n"
                    + "        }\n"
                    + "    ],\n"
                    + "    \"type\": \"231\"\n"
                    + "}";

    parseRobotConfigJson(patrolJson);
  }


  /**
   * 解析 机器人:/home/robot/robot_mr9/robot_patrol_data json
   * @param patrolJson
   */
  @SneakyThrows
  private static void parseRobotConfigJson(String patrolJson){
    List<RobotPatrolLine> robotPatrolLines = new ArrayList<>();
    ObjectMapper objectMapper = new ObjectMapper();
    ArrayNode arrayNode = (ArrayNode) objectMapper.readTree(patrolJson).get("patrol");
    for (JsonNode taskNode : arrayNode) {
      RobotPatrolLine robotPatrolLine = new RobotPatrolLine();

      String patrolNum = taskNode.get("patrol_num").asText();
      robotPatrolLine.setPatrolNum(patrolNum);

      List<AreaPoint> areaPoints = new ArrayList<>();

      AreaPoint areaPoint = new AreaPoint();
      areaPoint.setAreName("default");
      areaPoint.setPoints(new ArrayList<>());
      ArrayNode patrolPointArr = (ArrayNode) taskNode.get("patrol_point");
      for (JsonNode pointNode : patrolPointArr) {
        pointNode.get("point_x");
        Double pointX = pointNode.get("point_x").asDouble();
        Double pointY = pointNode.get("point_y").asDouble();
        areaPoint.getPoints().add(AreaPoint.Point.builder().pointX(pointX).pointY(pointY).build());
      }
      areaPoints.add(areaPoint);
      robotPatrolLine.setAreaPoints(areaPoints);

      robotPatrolLines.add(robotPatrolLine);
    }
    System.out.println(robotPatrolLines);
  }

}
